# This is a basic workflow to help you get started with Actions

name: Slack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  slack:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: archive/github-actions-slack@v2.0.0
        env:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        with:
            slack-channel: U02DM6Q95PV
            slack-text: Hello! Event  "{{ github.event_name }}" in "${{ github.repository }}" 🤓
