# This is a basic workflow to help you get started with Actions

name: Slack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master "branch"
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Thisworkflow contains a single job called "build"
  slack:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it .
      - uses: pullreminders/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"C02DF28U8CV\",\"slack-text\":\"Hello! Event  "{{ github.event_name }}" in "${{ github.repository }}" 🤓\"}'
      - name: Send Slack Message Result
        run: echo "${{ steps.send-message.outputs.slack-result }}"
      
      - uses: actions/checkout@master
        with:
           persist-credentials: false
           fetch-depth: 0
           run: |
             git add .
             git commit -m "new Commit"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

