name: Push on commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        MESSAGE: "There is a new commit!"
